localdb:
  image: postgres:11.2
  ports:
    - '5432:5432'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=adm
    - POSTGRES_PASSWORD=pswd
    - POSTGRES_DB=db

testdb:
  image: postgres:11.2
  ports:
    - '5433:5432'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=adm
    - POSTGRES_PASSWORD=pswd
    - POSTGRES_DB=test_db
