localdb:
  image: postgres:11.2
  ports:
    - '5432:5432'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=dockerAdmin
    - POSTGRES_PASSWORD=dockerPass
    - POSTGRES_DB=dockerNode

testdb:
  image: postgres:11.2
  ports:
    - '5433:5432'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=dockerAdmin
    - POSTGRES_PASSWORD=dockerPass
    - POSTGRES_DB=dockerNode
